[
 d888b  db    db d888888b      .d888b.      db      db    db  .d8b.  
88' Y8b 88    88   `88'        VP  `8D      88      88    88 d8' `8b 
88      88    88    88            odD'      88      88    88 88ooo88 
88  ooo 88    88    88          .88'        88      88    88 88~~~88 
88. ~8~ 88b  d88   .88.        j88.         88booo. 88b  d88 88   88    @uniquadev
 Y888P  ~Y8888P' Y888888P      888888D      Y88888P ~Y8888P' YP   YP  CONVERTER 

designed using localmaze gui creator
]=]

-- Instances: 6 | Scripts: 1 | Modules: 0 | Tags: 1
local CollectionService = game:GetService("CollectionService");
local G2L = {};

-- Players.juandiego01043.PlayerGui.ScreenGui
G2L["ScreenGui_1"] = Instance.new("ScreenGui", game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui"));
G2L["ScreenGui_1"]["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling;

-- Tags
CollectionService:AddTag(G2L["ScreenGui_1"], [[main]]);

-- Players.juandiego01043.PlayerGui.ScreenGui.Frame
G2L["Frame_2"] = Instance.new("Frame", G2L["ScreenGui_1"]);
G2L["Frame_2"]["BorderSizePixel"] = 0;
G2L["Frame_2"]["BackgroundColor3"] = Color3.fromRGB(0, 175, 2);
G2L["Frame_2"]["Size"] = UDim2.new(0, 334, 0, 194);
G2L["Frame_2"]["Position"] = UDim2.new(0, 222, 0, 32);


-- Players.juandiego01043.PlayerGui.ScreenGui.TextButton
G2L["TextButton_3"] = Instance.new("TextButton", G2L["ScreenGui_1"]);
G2L["TextButton_3"]["TextWrapped"] = true;
G2L["TextButton_3"]["BorderSizePixel"] = 0;
G2L["TextButton_3"]["TextColor3"] = Color3.fromRGB(54, 0, 0);
G2L["TextButton_3"]["BackgroundColor3"] = Color3.fromRGB(92, 144, 51);
G2L["TextButton_3"]["Size"] = UDim2.new(0, 162, 0, 56);
G2L["TextButton_3"]["Text"] = [[steal instant ]];
G2L["TextButton_3"]["Position"] = UDim2.new(0, 368, 0, 46);


-- Players.juandiego01043.PlayerGui.ScreenGui.TextBox
G2L["TextBox_4"] = Instance.new("TextBox", G2L["ScreenGui_1"]);
G2L["TextBox_4"]["CursorPosition"] = -1;
G2L["TextBox_4"]["BorderSizePixel"] = 0;
G2L["TextBox_4"]["BackgroundColor3"] = Color3.fromRGB(114, 255, 255);
G2L["TextBox_4"]["Size"] = UDim2.new(0, 158, 0, 66);
G2L["TextBox_4"]["Position"] = UDim2.new(0, 372, 0, 118);
G2L["TextBox_4"]["Text"] = [[]];


-- Players.juandiego01043.PlayerGui.ScreenGui.Steal Path2D
G2L["Steal Path2D_5"] = Instance.new("Path2D", G2L["ScreenGui_1"]);
G2L["Steal Path2D_5"]["ZIndex"] = 20;
G2L["Steal Path2D_5"]["Thickness"] = 1.9;
G2L["Steal Path2D_5"]["Name"] = [[Steal Path2D]];


-- Players.juandiego01043.PlayerGui.ScreenGui.Script instant
G2L["Script instant_6"] = Instance.new("LocalScript", G2L["ScreenGui_1"]);
G2L["Script instant_6"]["Name"] = [[Script instant]];


-- Players.juandiego01043.PlayerGui.ScreenGui.Script instant
local function C_6()
	local script = G2L["Script instant_6"];
	Local Local Script:Require/password:Key_BTR"Local/Steal instant (word)	
end;
task.spawn(C_6);

